-- Widen commit_sha from varchar(40) to varchar(128).
-- Git SHA-1 hashes are 40 chars, but workspace fingerprints generated by
-- deriveWorkspaceSnapshotIdentity() produce strings like
-- "workspace-<sha256_hex>" which exceed 40 chars. This caused ingestion
-- to fail on non-git repos with: "value too long for type character varying(40)".

ALTER TABLE snapshots ALTER COLUMN commit_sha TYPE varchar(128);
